name: CI
on:
  push:
    branches: [main]

jobs:
  require_acorn:
    name: Import Acorn
    strategy:
      matrix:
        node: [12.x, 13.x, 14.x, "14.0.0", 15.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm install
    - name: Test Node
      run: npm test
    - name: Test Tap
      run: npm run tap  
